[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.13"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tic_tac_toe = "6a9rKhtTGmCtKuxJCetCopbW5A5Z3A6hUsBq5mf1i3D"

[programs.devnet]
tic_tac_toe = "6a9rKhtTGmCtKuxJCetCopbW5A5Z3A6hUsBq5mf1i3D"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
format = "cargo +nightly fmt && prettier --write 'tests/*.ts'"
lint = "cargo clippy && yarn dlx eslint --ext .ts tests/"
generate-clients = "yarn ts-node ./scripts/generate-clients.ts"
