[package]
name = "play-game"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.5"
dirs = "6.0.0"
signature = "2.3.0-pre.5"
tokio = "1.43.0"
solana-transaction-status = "2.1.13"
solana-client = "2.1.13"
solana-sdk = "2.1.13"
solana-program = "2.1.13"
hex = "0.4.3"
